name: Metrics
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/metrics.yml"

permissions: { contents: write }
concurrency: { group: metrics, cancel-in-progress: true }

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: calendar-languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update calendar-languages"
          filename: metrics.calendar-languages.svg
          base: ""
          plugin_isocalendar: "yes"
          plugin_isocalendar_duration: half-year
          plugin_languages: "yes"
          plugin_languages_indepth: "yes"
          plugin_languages_details: "bytes-size, percentage"
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 15
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update repositories"
          filename: metrics.repositories.svg
          base: ""
          plugin_repositories: "yes"
          plugin_repositories_pinned: 4
