name: Metrics
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/metrics.yml"

permissions: { contents: write }
concurrency: { group: metrics, cancel-in-progress: true }

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update base"
          filename: metrics.base.svg
          base: "header, activity, community, repositories, metadata"
      - name: isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update isocalendar"
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: "yes"
          plugin_isocalendar_duration: half-year
      - name: calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update calendar"
          filename: metrics.calendar.svg
          base: ""
          plugin_calendar: "yes"
          plugin_calendar_limit: 1
      - name: stars
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update stars"
          filename: metrics.stars.svg
          base: ""
          plugin_stars: "yes"
          plugin_stars_limit: 4
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update languages"
          filename: metrics.languages.svg
          base: ""
          plugin_languages: "yes"
          plugin_languages_indepth: "yes"
          plugin_languages_details: "bytes-size, percentage"
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 15
      - name: stargazers
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update stargazers"
          filename: metrics.stargazers.svg
          base: ""
          plugin_stargazers: "yes"
          plugin_stargazers_days: 0
          plugin_stargazers_charts: "yes"
          plugin_stargazers_charts_type: graph
      - name: followup
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update followup"
          filename: metrics.followup.svg
          base: ""
          plugin_followup: "yes"
          plugin_followup_indepth: "yes"
          plugin_followup_sections: repositories
      - name: lines
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update lines"
          filename: metrics.lines.svg
          base: ""
          plugin_lines: "yes"
          plugin_lines_sections: "repositories, history"
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
      - name: repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update repositories"
          filename: metrics.repositories.svg
          base: ""
          plugin_repositories: "yes"
          plugin_repositories_pinned: 4
      - name: traffic
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: itsramananshul
          template: classic
          config_timezone: America/New_York
          output_action: commit
          committer_branch: metrics
          plugins_errors_fatal: "no"
          retries: 3
          retries_delay: 60
          committer_message: "chore(metrics): update traffic"
          filename: metrics.traffic.svg
          base: ""
          plugin_traffic: "yes"
